[package]
name = "tokio-vsock"
version = "0.3.0"
authors = ["fsyncd"]
description = "Asynchronous Virtio socket support for Rust"
repository = "https://github.com/rust-vsock/tokio-vsock"
homepage = "https://github.com/rust-vsock/tokio-vsock"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"
exclude = ["test_fixture"]

[dependencies]
bytes = "0.4.12"
futures = "0.3.11"
libc = "0.2.71"
nix = "0.17.0"
vsock = "0.2.1"
tokio = { version = "1.0.1", features = ["net"] }

[dev-dependencies]
sha2 = "0.9.0"
rand = "0.7.3"
tokio = { version = "1.0.1", features = ["macros", "rt", "io-util"] }
